Mark skipdownloaderrors as safe
git-lfs/git-lfs pull request #4468
Opened 2021-04-08 15:42 UTC by Timmmm

This option can't be used to do anything dangerous.

Fixes #4467

2021-04-10 05:10 UTC, chrisd8088 requested changes
Hey, thanks for the bug report and patch!

I think this should be OK, but I'm wondering if you would mind reordering the new lines so they fall in alphabetical order in the respective lists, something like the suggestions I added (and in one case, it could help fix another ordering typo in the docs).

Thanks again very much for this PR, and welcome to the project!

2021-04-10 05:10 UTC, chrisd8088 commented on config/git_fetcher.go
> +	"lfs.skipdownloaderrors",
One suggestion to keep these in alphabetical order:

```suggestion
	"lfs.skipdownloaderrors",
	"lfs.url",
```

2021-04-10 05:10 UTC, chrisd8088 commented on docs/man/git-lfs-config.5.ronn
> +- lfs.skipdownloaderrors
In this case, we might also fix the ordering of `lfs.{*}.access` and `remote.{*}.access` while we're at it.

```suggestion
- lfs.skipdownloaderrors
- lfs.url
- lfs.{*}.access
- remote.{name}.lfsurl
```

2021-04-11 14:38 UTC, Timmmm commented
Ooo I can just click buttons - fancy. Thanks for the quick reply!

2021-04-11 20:57 UTC, chrisd8088 approved these changes
Thanks very much, this looks good to me!  Thanks again for the bug report and patch; it's much appreciated.

2021-04-11 20:57 UTC, merged