ssh: avoid using -- where possible
git-lfs/git-lfs pull request #4741
Opened 2021-11-16 21:15 UTC by bk2204

In Git LFS version 3.0, we added support for understanding the GIT_SSH_VARIANT environment variable and its corresponding configuration option.  When we did so, we dropped the special-casing for program names and instead always used the -- setting for the default variant, "ssh". This variant represents OpenSSH, which as a program with normal POSIX option handling, supports -- just fine.

Unfortunately, not all clients do.  TeamCity's SSH client doesn't set the variant and also doesn't understand --.  We need to handle this case to prevent option injection in case someone tries to use a URL like "ssh://-oProxyCommand=exploit/", which could otherwise lead to arbitrary code execution.

However, we don't have to add this all the time, but only when the user-and-host portion starts with a dash.  The reason is that the only other place an attacker could inject an option is in the path, and the path is not a separate option by itself.  The path is always preceded by a command (either "git-lfs-authenticate" or "git-lfs-transfer" in a single option that contains the name of the command, the path, and the operation, separated by spaces.  As a result, option injection is not possible in the path since those commands don't take options.

Note that Git just dies in this case with a message like so:

  fatal: strange hostname '-oProxyCommand=exploit' blocked

Let's adopt this approach of using -- less often so that we can more gracefully deal with this case and fix some SSH clients, even if they really should learn to understand this option.

Fixes #4733

2021-11-19 08:10 UTC, chrisd8088 requested changes
The code changes here all look good, thank you!  It took me a while to wrap my head around what was changing, even though it's not particularly complex, mostly because I got myself mixed up about the test suite and test helper.

However, in the process of untangling myself, I did find some oddities about how the SSH arguments are processed by the test helper (I believe it can still be passed `--` in the default test case, for instance) and also that I could bork a test by setting `GIT_SSH_VARIANT`, and that when doing so one `grep` passed in an unexpected fashion.

Anyway, as a result I ended up putting together a [branch](https://github.com/chrisd8088/git-lfs/tree/dash-dash-ssh-tests) with a couple of additional commits that I think might be valuable.

If that doesn't look OK, though, the main thing I would suggest changing is just to in some way restore the handling of `--` in `t/cmd/lfs-ssh-echo.go` because it does, I believe, still get passed that end-of-options delimiter, so it should be looking for it in the default case.

2021-11-30 20:28 UTC, bk2204 commented
I've looked through your comments here and they all seem sensible and reasonable.  What I've done is squashed your first commit into mine, changing the commit message slightly and adding a co-author credit, so that we don't leave my commit with nonsensical behavior uncorrected, and then cherry-picked your second commit, since that seems like it's fine as it is.

Thanks for the thorough review, and hopefully what I've done is okay with you.

2021-12-01 07:50 UTC, chrisd8088 approved these changes
All looks good to me -- thank you for making this so tidy!

2021-12-01 14:22 UTC, merged

2022-01-17 14:28 UTC, chrisdjali-wrld3d commented
It's been several weeks since this was merged. What kind of timeframe can we expect for it to appear in a tagged release?

2022-01-17 20:04 UTC, chrisd8088 commented
We expect to do a release sometime this month (January), but of course that's always dependent on external factors (jobs, life, etc.) which may cause a delay.  But the expectation is for a release in January.