Prevent &{...}s(MISSING) message
git-lfs/git-lfs pull request #5822
Opened 2024-07-10 08:28 UTC by philip-peterson

When encountering an HTTP 413 error, a message like the following is displayed:

```
LFS: Client error &{%!!(string=http) %!!(string=) %!!(*url.Userinfo=<nil>) %!!(string=my.example.com) %!!(string=/git/redacted/redcated.git/info/lfs/objects/9c4bf89ecc9faef1abab8a0c27a349a34b30b6d5816c5352dc26e0ceded0963f/1119460) %!!(string=) %!!(bool=false) %!!(bool=false) %!!(string=) %!!(string=) %!!(string=)}s(MISSING) from HTTP 413
```

This patch changes it to something readable:

```
LFS: Client error http://my.example.com/git/redacted/redacted.git/info/lfs/objects/9c4bf89ecc9faef1abab8a0c27a349a34b30b6d5816c5352dc26e0ceded0963f/1119460 from HTTP 413
```

2024-07-10 17:29 UTC, chrisd8088 commented
Hey, thanks for the contribution!

This looks logical, at first glance, but it seems it does cause problems somehow; some of our CI tests are reporting things like:
```
Authorization error: %!s(MISSING)
Check that you have proper access to the repository%!!(MISSING)(EXTRA *url.URL=http://127.0.0.1:35771/storage/invalid4c48d2a6991c9895bcddcf027e1e4907280bcf21975492b1afbade396d6a3340?r=push-invalid-pushinsteadof)
```

So we'll have to investigate a bit more and figure out what the intended action is here in the different use cases.

2024-07-10 18:37 UTC, Watchara242540 requested changes
@philip-peterson wat2540noii

2025-02-28 20:59 UTC, chrisd8088 commented
Thanks again for this PR, @philip-peterson!

I've included your changes in PR #5998 along with some other revisions that help resolve the outstanding CI failures from this PR, and credited you on the relevant commit.

I believe that PR should fully resolve the problems you reported here, and so I'm going to close this PR.  Thank you again for identifying the bug and helping us to fix it!

2025-02-28 21:00 UTC, closed without merging

2025-02-28 22:23 UTC, philip-peterson commented
Great, thank you @chrisd8088 and thanks for maintaining this futuristic and forward-looking extension to Git.